### ISSUE TITLE
Why there isn't any Unity3D engine based graphic benchmark?

### ISSUE THREAD

**Issue by dubigrasu** [phoronix-test-suite/phoronix-test-suite#125]
Unreal 3/4 engines are well represented in the suite and some other more or less common engines as well, but Unity3D which is a very common (if not the most) engine used in Linux games is missing from the suite.
What's the reason?

**Comment by michaellarabel** [comment]
The reason is very simple: not aware of any Unity games that can be benchmarked in an automated manner. If you are aware of any Unity games that do have benchmark/timedemo functionality and can be scripted to run tests from startup/shutdown, feel free to reopen this thread or make a new post about it.

**Comment by dubigrasu** [comment]
Games no, but there are a number of Unity tech demos that can be used for this purpose, the same way Unreal 4 demos are used on Phoronix test suite.

**Comment by michaellarabel** [comment]
Do you have any links to these demos or documentation about how they can be used for benchmarking? From the ones I had seen over the years they didn't work out for benchmarking.


Sent via mobile.
-------- Original message --------From: dubigrasu <notifications@github.com> Date: 8/30/16  1:03 PM  (GMT-06:00) To: phoronix-test-suite/phoronix-test-suite <phoronix-test-suite@noreply.github.com> Cc: Michael Larabel <Michael@MichaelLarabel.com>, State change <state_change@noreply.github.com> Subject: Re: [phoronix-test-suite/phoronix-test-suite] Why there isn't any
  Unity3D engine based graphic benchmark? (#125) 
Games no, but there are a number of Unity tech demos that can be used for this purpose, the same way Unreal 4 demos are used on Phoronix test suite.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/phoronix-test-suite/phoronix-test-suite","title":"phoronix-test-suite/phoronix-test-suite","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/phoronix-test-suite/phoronix-test-suite"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dubigrasu in #125: Games no, but there are a number of Unity tech demos that can be used for this purpose, the same way Unreal 4 demos are used on Phoronix test suite."}],"action":{"name":"View Issue","url":"https://github.com/phoronix-test-suite/phoronix-test-suite/issues/125#issuecomment-243526642"}}}

**Comment by dubigrasu** [comment]
As they are, no, they can't be used since they need some mouse or keyboard input to start in flyby mode, but I can recompile them in default flyby mode. 
They have no usable logs (framedata etc) but they accept various resolutions/screen quality from the command line. In combination with Libframetime they should do alright.
I can compile them for Windows and Mac too, but not sure how you would extract the framedata there.

Two examples: 
https://www.youtube.com/watch?v=ARorKHRTI80
https://www.youtube.com/watch?v=iV-224nMwN8

What do you think?

**Comment by michaellarabel** [comment]
If you can compile a Linux build in default fly-by mode and provide information about the CLI arguments, I can give it a shot... PTS has long supported the ability to use libframetime, but in reality libframetime has worked far less ideally than people think it does and has run into various build/OS/driver issues, etc where it's mostly hit-or-miss.

**Comment by dubigrasu** [comment]
OK, too bad about libframetime (though it does work for me).
I imagine that someone with a solid Unity knowledge can add a framedata log feature for these demos, but personally I don't know how to do that (only played with Unity for few days).
Anyway, I'll likely build the demos tomorrow and provide the necessary info.

**Comment by dubigrasu** [comment]
OK, you can (hopefully) download the Courtyard demo from here:
https://drive.google.com/open?id=0B3g2Bb1NIhC6NXliUDRTWUtHTFE

**Comment by dragon788** [comment]
I would definitely be interested in testing a few of these as Unity has become a very strong cross platform game framework.
