### ISSUE TITLE
Gentoo and phoronix-test-suite issues

### ISSUE THREAD

**Issue by wmyrda** [phoronix-test-suite/phoronix-test-suite#128]
Gentoo decided to remove PTS from the tree  https://bugs.gentoo.org/show_bug.cgi?id=477798 as the package does not fully support portage (Gentoo package management tool). It is possible however that hence the bug report is old that the issue has been since fixed. I tried to give it a look using latest installation script https://gitweb.gentoo.org/repo/gentoo.git/plain/app-benchmarks/phoronix-test-suite/phoronix-test-suite-6.2.1.ebuild?id=1dc4a663afef9f5cba0809971293ffe866a55aa4 and using it for version 6.6.0 but seems it needs more love than previously as now it would not even list available tests

```
user@localhost` ~ $ phoronix-test-suite list-available-tests
/usr/bin/phoronix-test-suite: line 39: ./pts-core/hooks/startup/template.sh: access denied

[NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: pts 
[NOTICE] Failed To Fetch OpenBenchmarking.org Repository Data: system 

Phoronix Test Suite v6.6.0
Available Tests

No tests found. Please check that you have Internet connectivity to download test profile data from OpenBenchmarking.org. The Phoronix Test Suite has documentation on configuring the network setup, proxy settings, and PHP network options. Please contact Phoronix Media if you continuing to experience `problems.
```

Any chance to fix that? Install seems wrong also  as I get after install warning that are suppose to appear only when there is  such a problem but yet I have both set up

` \* PHP_TARGETS seems empty, php.ini file can't be configured.
- Make sure that PHP_TARGETS in /etc/make.conf is set.
- phoronix-test-suite needs the 'allow_url_fopen' option set to "On"
- for downloading to work properly.`

**Comment by michaellarabel** [comment]
I'm not aware of any Gentoo-specific issues and have run PTS recently on Gentoo and other Gentoo-based distributions. It's possible that a dependency or two may be old and outdated, but that's easily updatable via an XML file (pts-core/external-dependencies/xml/gentoo-packages.xml). It looks like the bug report complaint is that PTS installs the dependencies rather than the Gentoo package. That's because there's a heck of a lot of different possible dependencies depending upon what test(s) you want to run out of the hundreds available. You could add all the possible PTS dependencies as a dependency on your Gentoo package, but then it would be a big dependency chain where most users wouldn't use them all.

That output for your problem is likely not a PTS issue at all, it's likely due to your PHP configuration disabling allow_url_fopen or the like, which is preventing network access so PTS can download the test information from OpenBenchmarking.org.

So if you could try and verify you get network working with PHP, then PTS should work and if you do run into any Gentoo-specific issues feel free to let me know.

**Comment by lramage94** [comment]
@wmyrda I maintain a copy of phoronix-test-suite in my [personal overlay](https://github.com/lramage94/overlay/tree/master/app-benchmarks/phoronix-test-suite), and I also maintain the [package for alpine linux](https://github.com/alpinelinux/aports/tree/master/testing/phoronix-test-suite). If you need any help or are experiencing any bugs, please let me know and I can work those changes into my packages.
