### ISSUE TITLE
Enable configurable port specification

### ISSUE THREAD

**Issue by kkebb** [phoronix-test-suite/phoronix-test-suite#131]
As a user, I would like the ability to specify the port of the phoromatic server on the command line, instead of having it randomly selected. This would help a lot with the dockerization of PTS where I won't have to expose and publish a range of ports for the container in order to access the server.

**Comment by michaellarabel** [comment]
@kkebb have you tried specifying the port via the phoronix-test-suite.xml / user-config.xml configuration file? Or is there a reason it'd be better to specify it via the CLI rather than the configuration? If there's some reasoning, happy to add it.

**Comment by kkebb** [comment]
Fair enough, which configuration parameter should be set in order to configure the port?

**Comment by michaellarabel** [comment]
Should be RemoteAccessPort in the XML configuration file. But yeah can enable a env var option override to, can probably get around to it later today/tomorrow.

**Comment by kkebb** [comment]
Yea that would be nice actually.

Also, I configured the user-config.xml as per your note, however, for some reason whenever I startup the phoromatic server, it still doesn't pick it up. I placed the user-config.xml under
~/.phoronix-test-suite/
is there another location that phoromatic-server looks for the user-config.xml file? since the path I am using doesn't seem to work?

**Comment by michaellarabel** [comment]
Are you running it as root? If so then it's at /etc/phoronix-test-suite.xml 

Sent via mobile.
-------- Original message --------From: kkebb <notifications@github.com> Date: 10/5/16  7:17 PM  (GMT-06:00) To: phoronix-test-suite/phoronix-test-suite <phoronix-test-suite@noreply.github.com> Cc: Michael Larabel <Michael@MichaelLarabel.com>, Comment <comment@noreply.github.com> Subject: Re: [phoronix-test-suite/phoronix-test-suite] Enable configurable
  port specification (#131) 
Yea that would be nice actually.

Also, I configured the user-config.xml as per your note, however, for some reason whenever I startup the phoromatic server, it still doesn't pick it up. I placed the user-config.xml under

~/.phoronix-test-suite/

is there another location that phoromatic-server looks for the user-config.xml file? since the path I am using doesn't seem to work?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/phoronix-test-suite/phoronix-test-suite","title":"phoronix-test-suite/phoronix-test-suite","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/phoronix-test-suite/phoronix-test-suite"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kkebb in #131: Yea that would be nice actually.\r\n\r\nAlso, I configured the user-config.xml as per your note, however, for some reason whenever I startup the phoromatic server, it still doesn't pick it up. I placed the user-config.xml under\r\n~/.phoronix-test-suite/\r\nis there another location that phoromatic-server looks for the user-config.xml file? since the path I am using doesn't seem to work?"}],"action":{"name":"View Issue","url":"https://github.com/phoronix-test-suite/phoronix-test-suite/issues/131#issuecomment-251835808"}}}

**Comment by kkebb** [comment]
Yes I am - thanks for the prompt reply! I ended up figuring it out from the log messages that displayed when I ran the phoromatic server too!

**Comment by michaellarabel** [comment]
@kkebb with the latest Git ( https://github.com/phoronix-test-suite/phoronix-test-suite/commit/a26f2f5223a89a0435b105f48d46738d3ee05dfd ) you can now specify an HTTP_PHOROMATIC_PORT= environment variable to override the server's port selection, if it's easier for your purposes than modifying the conf file.

**Comment by dragon788** [comment]
Future visitors should note the above appears to be a typo/dyslexia, the actual ENV needing set is `PHOROMATIC_HTTP_PORT`.
