### ISSUE TITLE
multiple clients not being detected by phoromatic server

### ISSUE THREAD

**Issue by kkebb** [phoronix-test-suite/phoronix-test-suite#133]
So for some reason, when I run the phoromatic server, the clients that try to connect to it are only being detected under 1 client only. I believe I was able to get it to work with an older version of the phoromatic tool (not quite sure if it was 6.2.1 or 6.2.2) however, in 6.6.0 it seems to fail to detect the multiple clients that are connecting to it, and interprets the multiple clients as 1 client.

**Comment by michaellarabel** [comment]
Is this a lot of VMs connecting with perhaps the same IP or MAC address? If you can elaborate a bit on the configuration it would be helpful, but thinking it may be the case and there is a workaround if it's related to that. Or if it's not, are you copying the same phoronix-test-suite folder files to each of the systems under test? The core.pt2so file contains some identifier information where if that's getting copied to each system may think it's the same.

**Comment by kkebb** [comment]
That would explain quite a bit.

So, to answer your first question, yes this a bunch of VMs trying to connect to the phoromatic server however they don't have the same IP or MAC address as far as I know.. however, I am running them in docker containers so I am wondering if it is because of the fact that the docker engine across our VMs share the same IP address, if that is even relevant.

The second option that you are mentioning doesn't seem to be likely unfortunately since each "dockerized" client has unique core.pt2so contents. Please see screenshot.
<img width="1603" alt="screen shot 2016-10-06 at 9 52 32 pm" src="https://cloud.githubusercontent.com/assets/2312702/19176626/b4a6e7de-8c0f-11e6-9e98-cd8ea16c7a1a.png">

**Comment by michaellarabel** [comment]
@kkebb it sounds like it may be seeing it as the same IP address. Can you try editing the /var/lib/phoronix-test-suite/pts-core/phoromatic/public_html/phoromatic.php with a patch like:

`diff --git a/pts-core/phoromatic/public_html/phoromatic.php b/pts-core/phoromatic/public_html/phoromatic.php
index 27f82ee..d602ee3 100644
--- a/pts-core/phoromatic/public_html/phoromatic.php
+++ b/pts-core/phoromatic/public_html/phoromatic.php
@@ -154,6 +154,7 @@ if($PTS_MACHINE_SELF_ID != null)
        $result = $result->fetchArray();
 }
 
+/*
 if(!isset($result) || empty($result))
 {
        // If system was reloaded and MachineSelfID no longer matches but there is existing IP or MAC address claim against it
@@ -165,6 +166,7 @@ if(!isset($result) || empty($result))
        $result = $stmt->execute();
        $result = $result->fetchArray();
 }
+*/
 
 if(empty($result))
 {
`

Just commenting out that function as then it won't try to do the IP/MAC reclaim check. If that ends up working for you then, can work on making an option of it for a permanent solution.

**Comment by kkebb** [comment]
So just to clarify, that this is the snippet of code specifically that you are suggesting to be commented out:

    if(!isset($result) || empty($result))
    {
            // If system was reloaded and MachineSelfID no longer matches but there is existing IP or MAC address claim against it
            // XXX dropped LastIP = :ip_address OR
            $stmt = phoromatic_server::$db->prepare('SELECT Title, SystemID, Groups, State, MaintenanceMode, LastCommunication FROM phoromatic_systems WHERE AccountID = :account_id AND NetworkMAC = :network_mac');
            $stmt->bindValue(':account_id', ACCOUNT_ID);
            $stmt->bindValue(':ip_address', $_SERVER['REMOTE_ADDR']);
            $stmt->bindValue(':network_mac', $NETWORK_CLIENT_MAC);
            $result = $stmt->execute();
            $result = $result->fetchArray();
    }

**Comment by kkebb** [comment]
ping..

**Comment by michaellarabel** [comment]
Hi @kkebb I guess for some reason my response didn't show up. Yes, try commenting that out.

**Comment by kkebb** [comment]
So I just tested it, and it still doesn't work unfortunately.

Here are the steps that I am taking:
    
    0) # modify the phoromatic.php on both the server and the client
    1) vi /phoronix-test-suite/pts-core/phoromatic/public_html/phoromatic.php
    2) <comment out the block of code that you suggested>
    3) # run phoromatic server
    4) /usr/bin/phoronix-test-suite start-phoromatic-server
    5) # connect the client(s)
    6) /usr/bin/phoronix-test-suite phoromatic.connect <phoromatic-server>:8000/$CODE

Please let me know if there are any concerns with the steps I listed above or if I need to clarify anything.

**Comment by kkebb** [comment]
So, in the logs I see:

    [Tue Oct 11 15:31:03 2016] 172.32.1.62:46332 [200]: /phoromatic.php
    [Tue Oct 11 15:31:03 2016] 172.32.1.62:46333 [200]: /phoromatic.php
    [Tue Oct 11 15:31:27 2016] 172.32.1.63:43089 [200]: /phoromatic.php
    [Tue Oct 11 15:31:27 2016] 172.32.1.63:43090 [200]: /phoromatic.php
    [Tue Oct 11 15:31:31 2016] 172.32.1.62:46334 [200]: /phoromatic.php

Those IP addresses (i.e. 172.32.1.62/63) are from the clients, therefore there seems to be an indication that phoromatic is able to make a distinction, however, on the UI it doesn't prompt for an approval of the second server (depending on which one is added first).

**Comment by kkebb** [comment]
Also, what variable are you searching for in the code to determine the IP address?

**Comment by kkebb** [comment]
FYI: Here are the dependencies that I have installed within the container:
    RUN yum update -y && yum clean all \
             && yum install -y wget \
             which \
             xdg-utils \
             php-cli \
             php-xml \
             bzip2 \
             php-pdo \
             patch \
             glibc-static \
             automake \
             autoconf \
             make \
             gcc-c++ \
             SDL* \
             gcc \
             groupinstall 'Development Tools' \
             epel-release \
             yasm

**Comment by michaellarabel** [comment]
@kkeb you mean on the approval of the second *client* ?

$_SERVER['REMOTE_ADDR'] is used for obtaining the IP address.

Another debugging method would be running *phoronix-test-suite dump-core-storage* on the clients. Look at the lines of global_system_id and machine_self_id. Per-system those should be unique, are they for you?

**Comment by kkebb** [comment]
So, it seems that they are not unique per-system, however, this might be caused by interference by the fact that the phoronix installation is dockerized, thus since I am using the same docker image across the clients, the global_system_id, and machine_self_id will be identical.

Also, when I run

    echo $REMOTE_ADDR

within the client containers, the prompt returns an empty string.

**Comment by michaellarabel** [comment]
it's not $REMOTE_ADDR but $_SERVER['REMOTE_ADDR']  is a magic environment variable when paired with an X Server.

From your Docker instance are you able to remove the /var/lib/phoronix-test-suite/core.pt2so file so then it will be able to generate a unique ID for each deployed system?

**Comment by kkebb** [comment]
Removing the core.pt2so file work, thanks! I guess my workaround would be to add a **rm** command of the file within my Dockerfile. Is there any plan to support running multiple docker container pts-clients on the same VM and have them connect to the phoromatic server?

**Comment by michaellarabel** [comment]
I guess I'd need to see the Dockerfile or better understand the use-case to see about some alternative solution. I know there are many other PTS users using it within Docker and other containers without expressing any issues.

**Comment by kkebb** [comment]
So the use-case would be to do the following:
The containers divvy up the VM, thus a single CPU test on a VM isn't the same as multiple CPU tests inside containers, each of which has a number of reserved cores.

**Comment by kkebb** [comment]
Hey! Quick question, I would like to clarify which of the 2 following options are occurring:
1) Is the PTS client picking up it's IP address off the host and including in it's payload when communicating with the Phoromatic server?
OR
2) Is the Phoromatic server taking care of the PTS Client identification?

**Comment by michaellarabel** [comment]
1. PTS does read its IP address and MAC address on host. But for IP, the Phoromatic Server is looking at the originating IP address of the HTTP(S) connection. As part of all communications with Phoromatic, PTS does always include the NIC's MAC address and a self-generated ID number it comes up with on first run plus a globally-assigned random number upon first connection with OpenBenchmarking.org (if your system has an Internet connection.)

2. The Phoromatic Server makes use of the client's self-generated ID numbers to look for matches against previously connected systems otherwise falls back to looking at the network MAC address. Such as if you were wiping your disk and freshly loaded an OS on there and want to re-associate with that previous account.

Does that clear things up?

**Comment by kkebb** [comment]
Yep thank you!

**Comment by jamesk-arlut** [comment]
@michaellarabel I believe you closed this due to lack of people reporting it as an issue as opposed to it being fixed; just want to let you know in any case that it is still an issue.  I have recreated it using docker images I've built off of the phoronix/pts image (to install NVIDIA drivers in order to benchmark GPU performance).  My use case is, using either docker or kubernetes, I run one pts container as the phoromatic server and multiple pts containers as phoromatic clients (and/or using the host machine as an additional client), each with a different display variable screen setting, in order to run gputest and other graphics benchmarks on different monitors connected to my computer.  This is just my proof of concept setup right now; I intend to actually run the container images using kubernetes in a VMWare7 cluster with Bitfusion sharing a GPU across multiple compute server and display server/thin client configurations in order to benchmark how well the different display hardware configurations work.

I have verified that your workaround of removing /var/lib/phoronix-test-suite/core.pt2so in my client containers before trying to connect to the phoromatic server worked to let them be added to the server separately; now I plan to add that line to my dockerfile to update my server and client images, and rerun all of my tests to date to verify that doesn't break anything else.  The file does seem to have been automatically regenerated (with new identifiers) once I ran PTS to connect to the server.  But assuming that it is successful, I'd like to ask the question if it would make sense for you to update the phoronix/pts image to add that as well so that people don't have this issue moving forward.  Are there any other considerations of which I am not aware that would make that a bad idea?

I'll post again once I've rerun all of my testing to confirm whether or not it causes me any additional issues.

**Comment by jamesk-arlut** [comment]
@michaellarabel An update: I think deleting the /var/lib/phoronix-test-suite/core.pt2so in the phoronix client image build process solves my problem, though with some caveats.  When running in docker, since I assign an IP address to the container on runtime, the phoronix server correctly handles the container with a new PTS id, mapping it to the same system because the IP addresses match.  However, in kubernetes, pods do not have a way to assign an IP or MAC address or use the IP address assigned to a service as the outgoing IP.  So every time I run a new pod with the phoronix client image and new PTS IDs, it sees it as a new system.  I think this is acceptable for my use case, since I can set the server to auto-approve new systems when they connect, and go in and disable old systems for the deleted pods.  And since my containers have hostnames set, I am able to associate results run in different pods with the same hostnames for comparison purposes.

That being said, though I believe this is acceptable for my use case, at this point I don't know that I would recommend removing the file in the phoronix/pts image, as this behavior might not be acceptable to others.  It would be nice however if a section on considerations for running PTS (in standalone, phoronix server, and phoronix client configurations) in docker containers and with kubernetes could be added to the documentation at https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/documentation/phoronix-test-suite.md.  This section could address the implications of the /var/lib/phoronix-test-suite/core.pt2so file with its IDs being shared across different containers, and have recommendations for situations where that file should be removed to regenerate the IDs, as well as general instructions for getting set up to run in docker/kubernetes.
