### ISSUE TITLE
browser launching code

### ISSUE THREAD

**Issue by orbisvicis** [phoronix-test-suite/phoronix-test-suite#136]
# `pts-core/commands/gui.php`: If the browser is already open, the launcher terminates after connecting to an existing session. Then, both phoronix servers (http, websocket) are killed. I suggest a cli parameter to (pick one):
- pass a custom command
- require input anyway after launching browser (`read var_name`)

**Comment by michaellarabel** [comment]
Sorry for the late response. What browser are you using? The gui command already requires pressing enter to quit, for all browsers but Chrome/Chromium/ With Chrome/Chromium it uses --temp-profile and --app=, so it shouldn't open in an existing session, so there it doesn't need additional handling.

**Comment by michaellarabel** [comment]
The PTS GUI outside of PTS has been deprecated https://github.com/phoronix-test-suite/phoronix-test-suite/commit/4583696ccfced88386fad37a60f0cfd02a7d8429#diff-10be6ef5953958bd8a69ca45e5daf39d and as I haven't seen any push back or any enterprise interest in that localized HTML5 GUI solution, it will likely be removed soon. For those desiring a GUI interface, using Phoromatic is the preferred approach for controlling the system. There is also `phoronix-test-suite interactive` and `phoronix-test-suite shell` for those wanting a "guided" PTS CLI experience if the shell itself is otherwise intimidating.
