### ISSUE TITLE
OSX 10.5.8 - Cannot run phoronix-test-suite 6.x, due to php-5.2, suggestions?

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#142]
I can see that this is mentioned in the system requirements that php 5.3 is required and indeed the old machine is running 5.2. Is there a legacy client still available for older machines or another suggested way?

Here is how a launch looks.
./phoronix-test-suite phoromatic.connect 192.168.1.2:2001/ABC123

Parse error: syntax error, unexpected T_STATIC in /Users/adam/phoronix-test-suite/pts-core/objects/phodevi/phodevi_sensor.php on line 40

Stackoverflow regarding the error and php 5.2/5.3
http://stackoverflow.com/questions/4668557/parse-error-syntax-error-unexpected-t-static

**Comment by michaellarabel** [comment]
Right, PHP 5.2 was formally our base requirement while it's slowly crept up to PHP 5.3 for some functionality but I do a best-effort to try to retain compatibility with PHP 5.2 for core PTS functionality. Looks like this crept through...

Can you try Git or otherwise apply this new patch? https://github.com/phoronix-test-suite/phoronix-test-suite/commit/01b3030ef8ec8a62bb5507c954ad72b14fd88e57 It should just bypass the Phodevi sensors code when on PHP 5.2 now, so that it won't crash and all other Phoromatic functionality will continue to work. I believe I covered the main entry points but if you hit any other snags feel free to let me know.
