### ISSUE TITLE
Can't login from phoromatic-server. Can't reset password.

### ISSUE THREAD

**Issue by snigel** [phoronix-test-suite/phoronix-test-suite#143]
I can't login from the phoromatic-server web interface. 

I'm using the same login details as for openbenchmarking.org
Cannot reset password via openbenchmarking org, the reset link only tells me that I need to be logged in.

For the sake of it, I tried to reregister my account from the phoromatic web interface, but it detects that my username already taken.

**Comment by michaellarabel** [comment]
The Phoromatic accounts aren't associated with OpenBenchmarking.org.

If you try making a new username via the Phoromatic web interface does it work? You must have made one before via the Phoromatic web interface if it says the username is already taken.

**Comment by snigel** [comment]
Thank you. Then the reset password issue with openbenchmarking.org is secondary problem.

I could create a new username, it works fine. 
Is it possible to reset the password for phoromatic? I can't see anything in the web interface.

**Comment by michaellarabel** [comment]
At the moment on the Phoromatic web interface there isn't a means to reset a password short of wiping out the account. basically since there isn't necessarily a mail server running on the Phoromatic Server, can't do like an email based password reset. Could add a CLI option for forcing a password change to a Phoromatic account, but there isn't such method implemented at the moment.

**Comment by michaellarabel** [comment]
Just doing some tidying up and noticed this thread was still open. Since some months ago, when running `phoronix-test-suite phoromatic.set-root-admin-password`, the user is no longer prompted for the existing rootadmin password since it's fairly trivial check anyways and doesn't really offer any security value with the user already having shell access to the current user of the Phoromatic Server instance, so the fundamental issue of this thread has been resolved.
