### ISSUE TITLE
pts/machine-learning fails to install 

### ISSUE THREAD

**Issue by ZaidQureshi** [phoronix-test-suite/phoronix-test-suite#147]
Hi,

I have been trying to get the machine-learning test installed the whole day. All components are installed except caffe. All the necessary dependent packages I have installed through Fedora's official repos as well.
What happens is that while compiling caffe -lcblas and -latlas aren't linked so ld fails. The atlas library is installed and is available in my system at /usr/lib64/atlas. I assume cblas is like a part of atlas.
I have tried modifying the Makefile.config in the caffe-git directory that pts extracts, set BLAS_LIB set to the path I mentioned earlier and recompress to the tar.bz2 that pts is expecting. Still nothing. Any help in this matter will be helpful.

Does pts have to use a caffe install that it does itself? Can I try to compile and install caffe separately in my system so I have more control of  the linking?

Thanks.

**Comment by michaellarabel** [comment]
Caffe is somewhat of a special case due to having a large dependency chain and not all of those covered by PTS as on many distributions they aren't all covered or trivial. If you build Caffe by hand outside of PTS are you able to get it working? There is a system/caffe test profile available so if you have it installed system-wide (or in your PATH), you can use that by simply running: phoronix-test-suite benchmark system/caffe

**Comment by ZaidQureshi** [comment]
Ok I will try it out. Thanks.
