### ISSUE TITLE
pts/cachebench won't install

### ISSUE THREAD

**Issue by ZaidQureshi** [phoronix-test-suite/phoronix-test-suite#148]
I don't know why pts/cachebench won't install.

This is the log that is produced:

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/var/lib/phoronix-test-suite/test-profiles/pts/cachebench-1.0.0/install.sh: line 4: cd: llcbench/: No such file or directory
make: *** No rule to make target 'linux-mpich'.  Stop.
make: *** No rule to make target 'cache-bench'.  Stop.

**Comment by michaellarabel** [comment]
The issue is due to your gzip file appearing corrupt. I just verified the mirror is fine and the MD5/SHA256 matches are fine, but due to some fluke on your system or so, the llcbench .tar.gz file appears messed up. You can try removing ~/.phoronix-test-suite/installed-tests/pts/cachebench* so the file will re-download and the install should then work, assuming your system's tar command isn't somehow messed up.
