### ISSUE TITLE
Lightsmark missing files/dependencies

### ISSUE THREAD

**Issue by SteveEbey73742** [phoronix-test-suite/phoronix-test-suite#152]
shown here is the error returned with Lightsmark, when I try to run the 6.6 or 6.8 versions/

 E: ./backend: error while loading shared libraries: libGLEW.so.1.5: cannot open shared object file: No such file or directory

Since when does linux use drive letters? looks like something from a windows install may be catching me up, or a typo in the code?

**Comment by michaellarabel** [comment]
"E" is short for error.  libGLEW.so.1.5 is only packaged on older Linux distributions due to it being out of date, so there isn't an easy way to install it on newer distributions unless you build it from source or hack in an older RPM/Deb to work for you. Lightsmark is unfortunately closed-source so there isn't a way for us to make it updated for a newer libGLEW.
