### ISSUE TITLE
xdg-open should be the first choice in gui.php

### ISSUE THREAD

**Issue by atomsymbol** [phoronix-test-suite/phoronix-test-suite#156]
Hello

https://github.com/phoronix-test-suite/phoronix-test-suite/blob/1bf2f3239aa29cdfc681c9eeea5c6e95c60ee20e/pts-core/commands/gui.php#L84

I propose xdg-open to be the first option tried. Currently on my machine, PTS gui launches Firefox although I have configured my machine to launch Google Chrome in such situations (via KDE's system settings).

On my machine there is no "google-chrome" executable but there is "google-chrome-stable". On some other machine it might be "google-chrome-beta". In light of the fact that the executable is machine-specific (and user-specific), xdg-open should be the primary choice in gui.php.

**Comment by michaellarabel** [comment]
In terms of the (very experimental) GUI option, Chrome is used as the primary choice due to its `--temp-profile --app=` options making for a nicer, more app-like experience. At least last time I worked on that related code, Firefox didn't offer similar switches. And unfortunately the switches aren't standardized among web browsers, so using xdg-open would likely be a problem in that context too.

The PTS client itself when wanting to launch a browser to view results, it uses a different code-path.
