### ISSUE TITLE
Android port?

### ISSUE THREAD

**Issue by MineFuehrer** [phoronix-test-suite/phoronix-test-suite#165]
What's your take on [running phoronix in termux?](https://github.com/termux/termux-packages/issues/842)

Thx

**Comment by mtippett** [comment]
Hi Malleus,

There is nothing fundamentally preventing PTS running under termux.  In
fact, with minimal workarounds, I managed to run git PTS under termux this
morning.

1 Test To Install
        1MB Of Disk Space Is Needed

    pts/idle-1.1.0:
        Test Installation 1 of 1
        Installation Size: 0.01 MB
        Installing Test @ 14:47:12



Timed Idle:
    pts/idle-1.1.0
    System Test Configuration
Time To Idle (In Minutes)

Enter Value: 1



The main complexity is adapting pts to the packaging and file locations in
/data/data.  And choosing which tests have enough build capability to
compile and run under termux.


I would suggest that you look at if a maintainer for PTS can be found to
package pts into the termux package list which will help maintain the
termux behaviours.


Matthew

On Apr 2, 2017 05:58, "Malleus Germanorum" <notifications@github.com> wrote:

What's your take on running phoronix in termux?
<https://github.com/termux/termux-packages/issues/842>

Thx

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/phoronix-test-suite/phoronix-test-suite/issues/165>,
or mute
the thread

**Comment by MeinFuehrer** [comment]
Normally, phoronix keeps all its data in the user's home directory so it's not the main problem.  

What's the solution to the main issue, namely, the wrong sh and possibly other interpreters' paths?

**Comment by vishalbiswas** [comment]
The main problem that I discovered for doing this is that there is no way to modify the prefix globally. Even if the install prefix is changed, all underlying operations still use the standard linux prefix.

**Comment by michaellarabel** [comment]
@vishalbiswas can you elaborate more on the prefix you are referring to? It should already be possible if not very easy to change once I ensure your needs.

**Comment by vishalbiswas** [comment]
For ex: default script to run browser assumes shell in /bin, cache directories in /var/lib (or similar).
There are many locations where paths like these are absolute. Instead of this, I'd like to have something similar to`$PREFIX/bin`, `$PREFIX/var/lib`, etc

**Comment by lramage94** [comment]
Phoronix-test-suite does support prefixing, just read the installer script,
```shell
# To install into a chroot, set $DESTDIR to the corresponding directory.

if [ "X$1" = "X" ]
then
	INSTALL_PREFIX="/usr"
else
	INSTALL_PREFIX="$1"
fi
```
https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/install-sh

Support for Termux dependencies was just merged in https://github.com/phoronix-test-suite/phoronix-test-suite/commit/865156461a653302dbdc8af8f1a87a922b3a5a2a

I have also written a post on getting it running on my website,

https://lramage94.github.io/linux/android/benchmarking/testing/phoronix/gpl/termux/2018/05/18/pts-on-android/

**Comment by michaellarabel** [comment]
This thread is being closed to reflect the ongoing work in the newer thread with Termux having been merged, etc. https://github.com/phoronix-test-suite/phoronix-test-suite/issues/253

**Comment by vishalbiswas** [comment]
@lramage94 I was talking about things like this -> https://github.com/phoronix-test-suite/phoronix-test-suite/blob/ef96cd126ee043f37d8831cc1eb99d190b66c0b3/pts-core/pts-core.php#L112
