### ISSUE TITLE
Is it possible to specify paramters by using FIO/Stress-ng test suites

### ISSUE THREAD

**Issue by larrywongl** [phoronix-test-suite/phoronix-test-suite#168]
Hi,

Question 1:
It seems phoronix includes both FIO and Stress-ng as its test suites, that's really amazing, I am wondering if it is possible to set parameters(FIO/Stress-ng specified) from the CLI instead of the user interactive menu provided by default? and how about the profile containing group of parameters?

say for example, I want to stress the CPU up to 20% for the HUTs, however, I am not able to do it by using the interactive menu.

Question 2:
It seems that FIO/Stress-ng is not available for windows platform, are there similar test suites of them to stress up the CPU/Memu on windows platform?

Question 3:
If the Q2 is false till now, can I dockerize the phoronix image and use docker to stress the windows platform instead of install it natively on windows platform?

thanks and best regards
Larry Wang

**Comment by larrywongl** [comment]
are there any updates on this?

**Comment by michaellarabel** [comment]
At the moment there isn't a 'supported' way of inserting CLI strings to pass to tests rather than menu selections. So the modifications would need to be through the test's test-definition.xml/install.sh files.

The available Windows tests for the Phoronix Test Suite is quite limited due to time/interest constraints without any current commercial work for that platform. But you can easily run the Phoronix Test Suite in a Docker container or via the Windows Subsystem for Linux and you should have a great experience.
