### ISSUE TITLE
install universe has many errors Why not a flatpack that would include all the main tests?

### ISSUE THREAD

**Issue by mitcoes** [phoronix-test-suite/phoronix-test-suite#180]
I have just installed phoronix-test-suite from AUR, 

And phoronix-test-suite install universe is taking a long time, and is giving many errors

I think a future flatpack that would include a zip file with the 8 Gb tests and not several small archives where some of them fail will solve this issues and save some work.

**Comment by michaellarabel** [comment]
Most of those errors are likely due from URL changes for mirrors beyond our control or compiler issues. Wouldn't know without specific reports to know which test profiles may be causing issues for you.

Flatpak itself wouldn't address these problems for example in cases where a test is running into problems on your system. The Phoronix Test Suite can already make use of a download-cache and nothing stopping anyone from combining all of the download-cache into a tar,xz/similar and offering it as a single download, without the need for introducing any dependencies on Flatpak, etc. We don't offer a single download option since the vast majority of people only install select tests they are interested in, not having the bandwidth resources ourself for offering such a download package, and it's very rare I actually here of people wanting to run say all of universe.
