### ISSUE TITLE
Odd erros on RHLE 5 builds

### ISSUE THREAD

**Issue by gamkiller77** [phoronix-test-suite/phoronix-test-suite#198]
I am doing a system and OS bench march to show the diff of OS installed and hardware used.

The first couple cases are RHEL 5 and they all show the same error when starting up and then running the bench marks.

Googling did not find much on these errors.

`
PHP Warning:  posix_isatty(): cannot seek on a pipe in /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php on line 315

[NOTICE] posix_isatty(): cannot seek on a pipe in pts_client:315
Phoronix Test Suite v7.4.0
PHP Warning:  posix_isatty(): cannot seek on a pipe in /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php on line 315

[NOTICE] posix_isatty(): cannot seek on a pipe in pts_client:315
Server IP: isv-mtv5-tester.cisco.com
PHP Warning:  posix_isatty(): cannot seek on a pipe in /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php on line 315

[NOTICE] posix_isatty(): cannot seek on a pipe in pts_client:315
Server HTTP Port: 8080
PHP Warning:  posix_isatty(): cannot seek on a pipe in /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php on line 315

[NOTICE] posix_isatty(): cannot seek on a pipe in pts_client:315
Account ID: RGTL49

PHP Fatal error:  Call to undefined function sys_get_temp_dir() in /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php on line 1432`

**Comment by michaellarabel** [comment]
Hi, are you able to upgrade your PHP build? The error is due to out-of-date PHP present on EL5: PHP 5.1 which is no longer maintained upstream. 

You could always do a local new PHP build without installing system wide and just use it for PTS. 

Or it looks like PHP 5.3 might be available in RHEL5: https://access.redhat.com/solutions/161503

Let me know if any other questions, but basically that behavior isn't unexpected due to being on the very old PHP base. PTS targets PHP 5.2 and newer.

**Comment by gamkiller77** [comment]
This worked perfect then need to install a couple more extensions.  For those that do not have RH access these are the steps i took.

yum remove php php-common
yum install php53
yum install php-dom

Andy

**Comment by michaellarabel** [comment]
Great, cheers. On RHEL6+ and newer (or pretty much any other modern distro) you shouldn't run into any problems either.
