### ISSUE TITLE
Setting environment variables to change phoromatic/websocket ports doesn't consistently work

### ISSUE THREAD

**Issue by dragon788** [phoronix-test-suite/phoronix-test-suite#227]
It appears if I run eg `env PHOROMATIC_HTTP_PORT=9091 PTS_WEBSOCKET_PORT=9090 phoronix-test-suiite start-phoromatic-server` it only gets the web port right, and if I run `start-remote-gui-server` it won't start without a config file, and `env PHOROMATIC_HTTP_PORT=9091 PTS_WEBSOCKET_PORT=9090 phoronix-test-suite start-ws-server` gets the websocket port right, but then hung my terminal.

I'm working on defining some automatic scenarios to reproduce these, it could be that I just need to clear a cache somewhere.

**Comment by michaellarabel** [comment]
https://github.com/phoronix-test-suite/phoronix-test-suite/commit/046beec3187eacce98e02cc2b6cbf0d922a12b3c enables support in start-phoromatic-server for using PTS_WEBSOCKET_PORT. It wasn't previously supported since right now the Phoromatic Server doesn't make any real use of the WebSockets communication (though that should change moving forward).

Regarding the GUI server, no changes right now since I'm looking at probably removing it from a release soon as it hasn't been maintained in any serious manner in several years and similar functionality could largely be achieved by using Phoromatic.

**Comment by derduskenga** [comment]
how do I add environment when I am using phoromatic server to schedule tets?
