### ISSUE TITLE
System Info could be cached

### ISSUE THREAD

**Issue by alexandrul** [phoronix-test-suite/phoronix-test-suite#247]
Hi,

While investigation an issue with the 7zip test under windows, I had to run it multiple times.
However, on my server gathering the system info takes enough time to be annoying (the test fails in under 2 seconds, gathering system info takes more than 5 seconds).

Is it possible to cache the system info (eventually based on a config file option)?

**Comment by michaellarabel** [comment]
The Phoronix Test Suite's Phodevi (Phoronix Device Interface) has long offered the ability to support a tiered caching scheme of the hardware/software data and this is also supported on Windows. This allows the hardware/software information to not be cached, cached only for the duration of the program running (e.g. for disk mount options or other system hw/sw state unlikely to change while running PTS itself), or to cache the field until the system has been rebooted (such as for most users not hot-swapping their CPUs/GPUs or an OS upgrade).

This is supported and working on Windows, though still there are some delays on Windows leading to slower start-up time than PTS on Linux/macOS/BSD. From my limited testing this has been primarily due to the slower start-up time for powershell on Windows when making calls to it.

At this point I can't think of any other optimizations for speeding up the Windows hardware/software detection, granted, it only takes a few seconds so short of when debugging a test problem or other quick running scenario, it shouldn't be noticeable to end-users. If you come across a particular item that is rather slow or other specific issue, feel free to re-open this ticket or open another thread.

Thanks,
Michael
