### ISSUE TITLE
BAD URL error when downloading benchmark source from Github

### ISSUE THREAD

**Issue by sudden6** [phoronix-test-suite/phoronix-test-suite#254]
Hi,

I'm trying to write a test profile for the phoronix test suite for a small program I wrote (https://github.com/sudden6/m-queens).

However the process fails already when trying to download the source code from Github with this download.xml content:

```
<?xml version="1.0"?>
<PhoronixTestSuite>
  <Downloads>
    <Package>
      <URL>https://github.com/sudden6/m-queens/archive/v1.0.tar.gz</URL>
      <SHA256>c5c298a377aadd6f92695e337a6a48ca7321bcc7e41585fb847ee376e49ff8b5</SHA256>
      <FileSize>15200</FileSize>
    </Package>
  </Downloads>
</PhoronixTestSuite>
```

I get this error:
```
./phoronix-test-suite debug-test-download-links local/m-queens
Checking: local/m-queens

BAD URL: v1.0.tar.gz / https://github.com/sudden6/m-queens/archive/v1.0.tar.gz
```

In the end, if I get this running, it should be basically the same test as https://openbenchmarking.org/innhold/218d69a0fe0a3d8cd420586d1a1747a6ee576b00 but optimized for more modern CPUs. I would be very happy if you could make it part of your regular CPU and compiler benchmarks.

**Comment by michaellarabel** [comment]
Hi @sudden6 the downloading from GitHub seems to be an issue on GitHub's end AFAIK. I've encountered this issue for years but only ever seems to cause problems from the GitHub.com domain and not any of the dozens/hundreds of others where test file data ends up being hosted... Seems to be either due to GitHub dynamically generating their .tar.gz packages or having some sort of user-agent checking in place that tries to fend off 'bots' from downloading data.

Once you have the test profile in good shape, I would be happy to host the file to workaround this issue -- it's generally been the easiest way I've found to workaround this GitHub snafu.

Thank you for working on a new test profile.

With my Phoronix.com hat on now. assuming it works well on modern hardware and jives nicely with PTS, I am generally happy to add it to my test arsenal for usage on Phoronix.com.

**Comment by michaellarabel** [comment]
(Also if you don't know, for your temporary testing, you can place your file download from GitHub to ~/.phoronix-test-suite/download-cache/ or /var/cache/phoronix-test-suite/download-cache/ if running as root and PTS will use the filename and checksum for picking up the file automatically if they match rather than trying downloading from a URL.)

**Comment by michaellarabel** [comment]
@sudden6 I have now had the time to go through and review the test and got it uploaded to OpenBenchmarking - https://openbenchmarking.org/test/pts/m-queens-1.0.0

Thanks!

I did end up mirroring the file outside of GitHub. I re looked into the Github.com download issue and it's due to GitHub strict enforcing HTTPS, so if you don't have php-openssl or equivalent package installed, the download will fail. Since there isn't a strict PTS dependency on php-openssl, it's easier just re-mirroring it to ensure it works for everyone.
