### ISSUE TITLE
Add option to override default test directory for disk tests

### ISSUE THREAD

**Issue by wyoung** [phoronix-test-suite/phoronix-test-suite#258]
Per a comment by @michaellarabel [elsewhere](https://gist.github.com/anshula/728a76297e4a4ee7688d#gistcomment-2594474), you can override the directory used for disk tests by changing `EnvironmentDirectory` in the user's settings file, but that's awkward for a couple of reasons.

First, this is apparently the directory used to hold the downloaded tests, which means you've got one variable being used for two very different purposes. There must be consequences to changing it other than just setting the new testing target.

Second, editing an XML file is a bit of a hassle.

For motivation to change this current situation, consider a common scenario: the system under test has a small SSD for applications (including PTS!) and a large disk array for bulk storage. We'd like to test both the fast SSD and the big disk array separately.

I suggest two options for changing this to solve the second concern above:

1. An environment variable, such as `PTS_DISK_TEST_PATH`. This would allow specifying an override on a per-disk basis easy:

        $ PTS_DISK_TEST_PATH=/big/data/array ./phoronix-test-suite options...

2. Ask during the interactive test setup, giving the default as option 1, common alternatives like `/tmp` and `/usr/tmp` as other  options, and then as a final option allow the user to type a custom path.

**Comment by michaellarabel** [comment]
There is already support for a `PTS_TEST_INSTALL_ROOT_PATH` environment variable. When that is set to a valid directory, it will use that location for installing/running via that directory rather than via the EnvironmentDirectory specified in the user XML file. That should address your request for more easily overriding the default test directory and is supported by PTS going back years. But it isn't a tunable specific to disk tests for a number of different reasons that it wouldn't work out.
