### ISSUE TITLE
Support HTTP mirror for downloads

### ISSUE THREAD

**Issue by rossburton** [phoronix-test-suite/phoronix-test-suite#272]
There should be a way to specify a URL to look for downloads in, instead of just  ~/.phoronix-test-suite/download-cache/.  This way a cluster of machines could use a central cache.

**Comment by swarth100** [comment]
I believe there are settings to use a shared cache as Phoromatic Clients?

http://www.phoronix-test-suite.com/documentation/phoromatic.pdf (page 3)

```
Decentralized
Once the Phoronix Test Suite running on the Phoromatic Server has been able to cache all of the
OpenBenchmarking.org test files and the needed files for each test, Phoromatic with any Phoronix Test
Suite clients on your LAN can run fully decentralized without the need for a constant stream of
OpenBenchmarking.org communication or Internet connection for that matter. (The only exception
would be if your local systems don't have all their needed external dependencies and your system's
package manager would need to install components like a compiler or necessary system libraries.
```

- - - 

As a temporary workaround you could mount the directory into the filesystems of the various clients

**Comment by michaellarabel** [comment]
Yes this has actually already been supported for years. Via the DownloadCache config option you should be able to specify any HTTP-accessible path to the folder generated by `phoronix-test-suite make-download-cache` (there is a generated JSON file that is queried by that, rather than just a bunch of random files in a directory).

That has been supported going back many years, but in recent years the preferred path is through running a Phoromatic Server. Even if you don't want to use the Phoromatic Server for results aggregation or any of its other many features, it does have built-in download-cache functionality.

Running
`phoronix-test-suite make-download-cache pts/all
phoronix-test-suite start-phoromatic-server`
(or using the systemd unit. Is enough to get it working with a HTTP server, etc.)

From the clients. you can then specify the Phoromatic Server URL/port from your config file and it will automatically be used as an automatic download cache.

The other benefit of using the LAN download cache via the Phoromatic Server is that if Avahi is on the client/server, new clients on your network will automatically discover the Phoromatic Server and use it as a download cache, so then you don't even need to do any configuration to the clients...

Let me know if either of these methods don't work out for you or have other questions, but using HTTP mirror for downloads is indeed fully supported.
