### ISSUE TITLE
darktable - line 3: $LOG_FILE: ambiguous redirect

### ISSUE THREAD

**Issue by rbn920** [phoronix-test-suite/phoronix-test-suite#280]
I am trying to run the darktable test in Arch. Nothing looks wrong in the logs created with `debug-run` but the tests fail. I tried running the commands manually an i get the output `./darktable: line 3: $LOG_FILE: ambiguous redirect`

Any help is appreciated.

**Comment by swarth100** [comment]
Try exporting the LOG_FILE variable before running the test.

```
export LOG_FILE="test.log"
```

---
It should be due to the `LOG_FILE` variable being exported by Phoronix during runtime.
To check this, see if it's in `env`:
```
env | grep -i "LOG_FILE"
```
This should return nothing nornally, or "test.log" if you run it after the export.

*NOTE*: If you run a pts test manually, make sure to provide the correct sequence of command line arguments.

**Comment by rbn920** [comment]
That allowed me to run it and it created a file the same as the `debug-run` command. I will close this issue but I am still having trouble with the test reporting that it fails and there are no results.
