### ISSUE TITLE
Uploads part of benchmark even though it was interrupted.

### ISSUE THREAD

**Issue by 38github** [phoronix-test-suite/phoronix-test-suite#289]
I ran a comparison benchmark and I interrupted (Ctrl+C) benchmark in the middle of it. Even though I did this it uploaded the system information but did not include anything in the graphs. Look at https://openbenchmarking.org/result/1808300-AR-1808301AR12 There are five computer/profiles/names registered but only the four successfully run benchmark are in the graphs.

**Comment by michaellarabel** [comment]
Hi @38github I am not sure I understand the issue.... It's intentional that PTS does allow interrupted results to be uploaded. As long as there are any results in the result file -- including from other runs -- it supports uploading that data to OpenBenchmarking.org. In that result file you mention there are indeed other runs in this result file so while you interrupted the testing of the latest run, it still intentionally allows you to upload the existing data.
