### ISSUE TITLE
Root rights issue.

### ISSUE THREAD

**Issue by Achaean** [phoronix-test-suite/phoronix-test-suite#322]
**Hi!** :-)

I installed the latest version (8.4.1) via the DEB package.
Question: Is it good for other distros as well, or only for Debian and Ubuntu?
(I mean, Debian based ones). :-)

If not, please invalidate this report.

PTS doesn't seems to handle well the rights elevation.
Since it will go to install dependencies or running a test who needs root rights, it brings up a box and asks for the root pwd, and after that fails.
No dependencies installation, nor testing as root.

**Happy New Year** everyone!!! :-)

**Comment by michaellarabel** [comment]
Yes you can use the Debian package for other distros that support DEB packages.

PTS handles the dependencies and root requirements dynamically. Installing all the possible dependencies would be massive as there are dozens of dependencies based upon the possible tests -- over a thousand different tests possible. So rather than installing all possible dependencies, it will install what are needed when installing the test.

Likewise, not all tests require root, only a few do. So if a test needs root, it will prompt the user when the time comes rather than forcing all tests to run as root.

**Comment by Achaean** [comment]
Then, like I said, it can't here install the dependencies and if some tests, require root console, it can't run those tests.
Bye!
