### ISSUE TITLE
-march=native option causes gcc compilation failure on POWER9 systems

### ISSUE THREAD

**Issue by aperezbios** [phoronix-test-suite/phoronix-test-suite#333]
IBM POWER8/9 GCC does not have --march=native, and when any phoronix test is run, it always returns "ERROR: gcc: error: unrecognized command line option ‘-march=native’; did you mean ‘-mcpu=native’?"

Using -mcpu=native instead solves this problem.

**Comment by johnjmar** [comment]
On which benchmarks have you encountered this issue?

**Comment by michaellarabel** [comment]
Found a few test profiles where their build system does set '-march=native' by default. I did think of a way to universally address this though rather than needing to update per-test-profile in this case...

The Phoronix Test Suite uses the notion of a 'compiler mask' to basically intercept what calls are passed to the compiler. This is used so PTS can report what compiler flags (namely, -O3 -march etc) were passed to the compiler for each test profile in order to be able to report it to the graphs, etc.

With the latest Git code, I've now added a check so on PPC architectures, it will automatically replace any '-march=' references with '-mcpu=' so it's enough to satisfy the compiler.

The change [ https://github.com/phoronix-test-suite/phoronix-test-suite/commit/fbc7dd50a0e1ee9425633cbae857598b94f68f2b ] is in place and will be found in PTS 8.6.1 stable later this month. Did some checks on a Talos II and it was enough to satisfy the few niche cases as well as if accidentally (or having it scripted) setting -march=native as part of the CFLAGS/CXXFLAGS that it will get translated to -mcpu=native.
