### ISSUE TITLE
Question: Is PTS supported for android

### ISSUE THREAD

**Issue by 1kapilgupta1** [phoronix-test-suite/phoronix-test-suite#351]
Is PTS supported for android? If yes, is there git already available.?

**Comment by michaellarabel** [comment]
There was a basic PTS client port of the Phoronix Test Suite done to Android a number of years ago, but hasn't been touched since due to no enterprise customers for that effort right now. Some elements of that code are still in PTS itself but not actively maintained and it's also a matter of what test profiles may work on Android. At this point there are no further plans around PTS on Android unless a commercial need arises or someone is looking to contribute the port.

**Comment by 1kapilgupta1** [comment]
Can you please give me a pointer on that PTS client port done to android? I want to check what all profiles will work on Android.

Thanks.
