### ISSUE TITLE
Unable to set rootadmin password for phoromatic started from systemd

### ISSUE THREAD

**Issue by jallen-amd** [phoronix-test-suite/phoronix-test-suite#384]
Running phoronix-test-suite phoromatic.set-root-admin-password from the command line seems to have no effect on a phoromatic server that was started from the systemd service. Is there an alternate way to set the root admin pass for this type of deployment?

**Comment by michaellarabel** [comment]
Hi John, can you elaborate a bit on what you are experiencing? Internally I and am aware of others that do use set-root-admin-password for the Phoromatic webUI root user + in conjunction with the systemd service without issue. It should work without having rebooted the server (or restarting the systemd service), but have you tried doing either? Or otherwise more details would be useful in trying to figure out if there's a bug at play or some unhandled use-case.

**Comment by jallen-amd** [comment]
I think I figured out the problem. I had been running "phoronix-test-suite phoromatic.set-root-admin-password" as my user and the systemd deployment defaults to running phoromatic as root.

I just added:
User=<user> and Group=<group> under the [Service] section of the service file so it runs in a user context.

So, no bug here, just systemd related confusion on my part.
