### ISSUE TITLE
Question: documentation of bisect and KVM

### ISSUE THREAD

**Issue by brauliobo** [phoronix-test-suite/phoronix-test-suite#387]
Hi, I want to track some performance issues on Linux and KVM using bisect.

Unfortunetely I couldn't find any documentation on how to use PTS and bisect. Also is there any automation available and documentation for KVM/QEmu?

**Comment by michaellarabel** [comment]
PTS in KVM/QEMU behave just the same as if running on bare metal, so there is no KVM/QEMU specific documentation.

There is/was a bisecting module in the public PTS Git tree though unfortunately without documentation. Due to time/resource constraints I haven't been able to maintain it in a few years but if digging through the Git history it should still be there and presumably work fine, I have heard others using it. But it basically just automated the good/bad passing to git bisect. So even without any PTS module you can simply use PTS in between your manual git bisect/good entering to see if a given commit matches your performance expectation or not.
