### ISSUE TITLE
hl2lostcoast test not running

### ISSUE THREAD

**Issue by melo0187** [phoronix-test-suite/phoronix-test-suite#40]
Steam installed, hl2: lost coast installed, latest phoronix cloned from git and installed by using install-sh.

Test fails to run no matter what. Without steam client running, with steam client running, without the game running, with the game running... nothing and I can't find any documentation about how I'm expected to run this specific test or what it expects me to do so it can run.

Please let me know what I'm doing wrong, how I can provide further information and I will be happy to do so.

**Comment by melo0187** [comment]
Here is my output of phoronix-test-suite system-info. Just in case that helps...

```
Phoronix Test Suite v5.6.0m0
System Information

Hardware:
Processor: AMD Phenom II X4 965 @ 3.40GHz (4 Cores), Motherboard: ASRock 870 Extreme3, Chipset: AMD RX780/RX790, Memory: 8192MB, Disk: 256GB Samsung SSD 840, Graphics: MSI NVIDIA GeForce GTX 760 2048MB (540/3004MHz), Audio: AMD SBx00 Azalia, Monitor: SAMSUNG, Network: Realtek RTL8111/8168/8411

Software:
OS: Ubuntu 14.10, Kernel: 3.16.0-23-generic (x86_64), Desktop: Unity 7.3.1, Display Server: X Server 1.16.0, Display Driver: NVIDIA 331.113, Compiler: GCC 4.9.1, File-System: ext4, Screen Resolution: 1920x1080
```

**Comment by michaellarabel** [comment]
Unfortunately for the tests that depend on Steam, it's rather a mess always to do automated testing with them. My only recommendation would be to look at ~/.phoronix-test-suite/test-profiles/pts/hl2lostcoast*/install.sh and try to run those commands one-by-one on your system from the terminal... Chances are one of the paths changed on your system by steam, some library path is needed/not-needed anymore, etc. Or might be due to capitalization issues with your Steam install.
