### ISSUE TITLE
CPU benchmark pts/indigobench-1.0.2 implicitely uses OpenCL on GPUs, skewing results 

### ISSUE THREAD

**Issue by luziferius** [phoronix-test-suite/phoronix-test-suite#418]
It seems that pts/indigobench-1.0.2 uses OpenCL if available, which skews the results.
As far as I can tell, the indicated benchmark should be a CPU-only test.

I have an AMD Ryzen 7 3700X.
These results (https://openbenchmarking.org/result/1911252-AS-1911042HU36) indicate that I should get about 1.4MSamples/s as a result. You can see the expected result in the screenshot below.
But I actually get this as the final result, beating an AMD Ryzen Threadripper 2990WX 32-Core CPU:
https://openbenchmarking.org/result/2002107-HU-1809200AR44

The test itself indicates that it runs on the GPU using OpenCL:
![IndigoBench](https://user-images.githubusercontent.com/2143820/74153501-1218ed80-4c11-11ea-9f09-3079cc8bcd88.png)

It seems that the Benchmark reports the combined result only.

**Comment by michaellarabel** [comment]
Yes there are some issues due to the upstream IndigoBench not allowing CLI switches to explicitly rely upon GPU/OpenCL or CPU rendering, so for OpenCL-enabled systems it is OpenCL testing rather than CPUs. Unfortunately until such CLI switches exist with that proprietary program there will be that issue.

**Comment by luziferius** [comment]
Sad to hear, but understandable then.

**Comment by michaellarabel** [comment]
Forgot to update this ticket but newer IndigoBench program releases do finally behave nicely with new CLI switches for GPU/CPU acceleration controls.

The PTS test profile since November in turn has been using this new IndigoBench and thus does happen to address this issue - https://openbenchmarking.org/test/pts/indigobench
