### ISSUE TITLE
ExtraData and FileFormat

### ISSUE THREAD

**Issue by davidovitch** [phoronix-test-suite/phoronix-test-suite#434]
I am trying to add support for extracting the render time for each frame from to the X-Plane11 test profile, but I can't figure out how to reverse engineer the required format.

There are various methods already implemented (that seems to happen here [pts-core/objects/pts_test_result_parser.php](https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/objects/pts_test_result_parser.php#L226)) that can parse this out when appended to the `$LOG_FILE` environment variable. These methods seem to be set via `<ExtraData>` in `results-definition.xml`. Additionally, the `<FileFormat>` can also be used. But what are than the corresponding formatting requirements?

So far I found that:

*  `<FileFormat>` can be `CSV` or `XML`
*  `<ExtraData>` can be `cpu-frames-space-delimited`, `csv-f1-frame-times`, `csv-individual-frame-times`, `com-speeds-frame-latency-totals`, `libframetime-output`, or `gpu-frames-space-delimited`

What are the corresponding format descriptions, and can someone provide some examples?

**Comment by michaellarabel** [comment]
Hi @davidovitch do you have a sample output of the render time you are trying to get from X-Plane 11? That might be the easiest way for showing how to parse it, I don't recall seeing the render time previously exposed by X-Plane.

**Comment by davidovitch** [comment]
you'll need to first add `--verbose` to the launch options in `<Arguments>` of the `test-definitions.xml`, and then your `Log.txt` output from X-Plane will look like this:
```
...
FRAMERATE TEST: time=93.1, frames=5563, fps=59.78
GPU LOAD: time=93.1, wait=25.7, load=27.6%
FRAME 0:  CPU: 1.412987 GPU: 0.003058 Total: 0.058672 Time: 8.517682
FRAME 1:  CPU: 1.412987 GPU: 0.003058 Total: 0.060073 Time: 8.567933
FRAME 2:  CPU: 1.412987 GPU: 0.003058 Total: 3.496210 Time: 8.618184
...
FRAME 5571:  CPU: 0.011301 GPU: 0.006255 Total: 0.015602 Time: 101.428258
FRAME 5572:  CPU: 0.011301 GPU: 0.006255 Total: 0.016741 Time: 101.436363
Clean exit from threads.
...

**Comment by michaellarabel** [comment]
Thanks, checking it out now.

**Comment by davidovitch** [comment]
For OpenArena the `ExtraData/Identifier` is set to `com-speeds-frame-latency-totals` and the format looks like this:

```
...
CL_InitCGame:  1.56 seconds
17 msec to draw all images
Com_TouchMemory: 0 msec
frame:0 all:  1 sv:  0 ev:2050 cl:  0 gm:  0 rf:  0 bk:  1
frame:1 all: 27 sv:  0 ev:  0 cl:  1 gm:  0 rf:  0 bk: 26
frame:2 all:  4 sv:  0 ev:  0 cl:  1 gm:  0 rf:  0 bk:  3
Jenna^7 does a back flip into the lava.
frame:3 all:  2 sv:  0 ev:  0 cl:  1 gm:  0 rf:  0 bk:  1
frame:4 all:  2 sv:  0 ev:  0 cl:  0 gm:  0 rf:  0 bk:  2
...
frame:3394 all:  5 sv:  0 ev:  0 cl:  1 gm:  0 rf:  0 bk:  4
frame:3395 all:  4 sv:  0 ev:  0 cl:  0 gm:  0 rf:  0 bk:  4
frame:3396 all:  4 sv:  0 ev:  0 cl:  0 gm:  0 rf:  0 bk:  4
frame:3397 all:  4 sv:  0 ev:  0 cl:  0 gm:  0 rf:  1 bk:  3
3398 frames 10.0 seconds 341.3 fps 1.0/2.9/26.0/1.1 ms
----- Client Shutdown (Client quit) -----
```

**Comment by michaellarabel** [comment]
The "ExtraData/Identifier" is a ~decade ago method that wouldn't be recommended for new tests unless it happens to be compatible with the output of any new test.... It relies upon hard-coded parsers within PTS like "com-speeds-frame-latency-totals" being hard-coded format for id Tech 3 era games. In the years since, the PTS result parser infrastructure has become much more flexible and capable of representing more capabilities via its XML-based syntax without needing changes to PTS itself as well as the ability to support multiple result outputs. Admittedly, the documentation on test profile is lacking due to time/resource constraints.

In the case of X-Plane 11, the test profile is now available as pts/xplane-1.1.2. It ends up just needing this to the result-definition (and --verbose now appended to Arguments in the test definition) for adding the frame times as a secondary output/graph:

`  <ResultsParser>
    <OutputTemplate>FRAME 12:  CPU: 1.292760 GPU: 0.007053 Total: #_RESULT_# Time: 8.948935</OutputTemplate>
    <LineHint>FRAME </LineHint>
    <ResultBeforeString>Total:</ResultBeforeString>
    <MultiMatch>REPORT_ALL</MultiMatch>
    <MultiplyResultBy>1000</MultiplyResultBy>
    <ResultScale>ms</ResultScale>
    <ResultProportion>LIB</ResultProportion>
    <AppendToArgumentsDescription>Per Frame Timing</AppendToArgumentsDescription>
  </ResultsParser>`

Note depending upon your PTS release you might need to be on Git / https://github.com/phoronix-test-suite/phoronix-test-suite/commit/12cc37654d087afb156dde85c8dbeb3b3292145a patch as a recent regression was uncovered in the code path for using one of the features.

**Comment by michaellarabel** [comment]
Here's an example run with the new output - https://openbenchmarking.org/result/2004107-PTS-XPLANEVE17

**Comment by davidovitch** [comment]
Thanks, that looks great! This can at least serve as a nice up-to-date example for the time being until magically someone adds this to the docs :-)
