### ISSUE TITLE
terminal colours contrast too similarly with background 

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [phoronix-test-suite/phoronix-test-suite#436]
![term-colours](https://user-images.githubusercontent.com/16513742/80291167-29ad4000-8743-11ea-9ea7-691158c076d1.png)
As shown, it is very difficult to read these sections. 

"       To change behavior, run: 
        echo performance | tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

        Reference: https://openbenchmarking.org/result/1706268-TR-CPUGOVERN32

        To stop showing performance tips, run: phoronix-test-suite unload-module perf_tips"

**Comment by michaellarabel** [comment]
Yes this is a known issue but unfortunately one that is difficult to manage nicely for all terminals/environments.... Unfortunately to my knowledge there is no way of being able to properly query what the background color is for a given terminal configuration, which makes being able to decide what color pallette to use difficult but would be happy to learn otherwise or if there is some other novel solution for dealing with terminal colors short of force overriding the background color.

**Comment by aromanos** [comment]
As an alternative, what about adding support for the NO_COLOR environment variable? This way we let the users with dark backgrounds to optionally specify it and get a fully readable output on default text and background colors. There's a growing list of software respecting it: https://no-color.org/

**Comment by michaellarabel** [comment]
Sure thing @aromanos in the latest PTS Git, NO_COLOR is now honored.
