### ISSUE TITLE
Provide a SNAP or FLATPAK build for linux

### ISSUE THREAD

**Issue by yaminb** [phoronix-test-suite/phoronix-test-suite#445]
Would be nice to have a SNAP or FLATPAK build for easy install/update on linux platforms, in my case Ubuntu.

**Comment by michaellarabel** [comment]
Due to the sandboxing nature among other restrictions imposed and the Phoronix Test Suite's wide selection of benchmarks and use-cases making tightening of credentials difficult, there are no plans to create a Flatpak/Snap version at this point.

For Ubuntu it would be recommended to download the Debian package or build from source otherwise if just wanting to locally run PTS from a given directory without a system-wide installation.
