### ISSUE TITLE
Cannot start result viewer server (locking twice the same lock)

### ISSUE THREAD

**Issue by kohoutovice** [phoronix-test-suite/phoronix-test-suite#447]
Hello,
I just trying to start result viewer server and it just not possible without some tweaks in code itself. 
Because it always print a message:

    [PROBLEM] The result viewer is already running. 

But I am sure that's not true. So i found out that if in file "**phoronix-test-suite/pts-core/commands/start_result_viewer.php**"
just comment out these lines:

    if(pts_client::create_lock(PTS_USER_PATH . 'result_viewer_lock') == false)
    {
         trigger_error('The result viewer is already running.', E_USER_ERROR);
         return false;
    }

I inspected it a little more and i discovered that it caused by the **function __startup**  in 
pts-core/modules/load_dynamic_result_viewer.php that is locking the same lock a little sooner. 
So Iam almost sure that one of those locking routines should be removed (probably the one in dynamic_result_viewer file).

**Comment by michaellarabel** [comment]
Thanks for the report.

The entirety of `start-result-viewer` is actually deprecated / no longer relevant. That pre-dated the dynamic result viewer module that is loaded by default when running the PTS. It's been that way since PTS 9.0 so the result viewer web process is running in the background. Thus the start-result-viewer is no longer needed as that was primarily when prototyping the dynamic result viewer. So the command has been effectively deprecated / not needed but I overlooked it in just deleting most of it.

The latest PTS Git should now delete all of the logic from the command and just print the result viewer URL/port that was started by the module code. So should be all more clear now and when running `start-result-viewer` will no longer cause any locking contention but just provide the information the user was after anyhow in trying to access the result viewer.
