### ISSUE TITLE
Multiple copies of the same input files unnecessarily waste disk space

### ISSUE THREAD

**Issue by zoidby** [phoronix-test-suite/phoronix-test-suite#478]
For example:

```
> find .phoronix-test-suite/ -name Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z
.phoronix-test-suite/installed-tests/pts/x265-1.2.0/Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z
.phoronix-test-suite/installed-tests/pts/rav1e-1.3.1/Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z
.phoronix-test-suite/installed-tests/pts/x264-2.6.1/Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z
.phoronix-test-suite/installed-tests/pts/aom-av1-2.1.2/Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z
.phoronix-test-suite/installed-tests/pts/x265-1.3.0/Bosphorus_1920x1080_120fps_420_8bit_YUV_Y4M.7z
```

Or:

```
> find .phoronix-test-suite/ -name Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m
.phoronix-test-suite/installed-tests/pts/x265-1.2.0/Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m
.phoronix-test-suite/installed-tests/pts/rav1e-1.3.1/Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m
.phoronix-test-suite/installed-tests/pts/x264-2.6.1/Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m
.phoronix-test-suite/installed-tests/pts/aom-av1-2.1.2/Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m
.phoronix-test-suite/installed-tests/pts/x265-1.3.0/Bosphorus_1920x1080_120fps_420_8bit_YUV.y4m
```

Are all the same files. Bit by bit.

Keeping multiple copies of them seems wasteful.

I was able to free 9.7 GiB by using hardlinks instead!

An alternative to hardlinks would be to save input files in a common directory.

Lastly, is there a reason to not delete the compressed files after successful installation altogether?

**Comment by michaellarabel** [comment]
Some test profiles may share common input files or other assets, and can be compared with their hashes in the downloads file, but no guarantees are made that the files are not modified later on by the test profile scripts, etc. Of course some generally safe assumptions could generally be made if the input file is a compressed file it's likely to be just extracted and not modified, but there are also other file types downloaded as well. So the current solution is to just download files on a per-test basis especially when the vast majority of files are quite small and thus not too worth it to worry about deduplicating them, it's really just the video encode/decode tests that deal with very large files that are common among tests.

From the Phoronix Test Suite user configuration file there is a `SymLinkFilesFromCache` option if wanting to just symlink the files from the download cache.

The files are not deleted after install since it avoids excess bandwidth/time re-downloading the files if reinstalling the test for changing out the CPU/compiler / other factors when you may want to re-install a test. But the user configuration file does also have the `RemoveDownloadFiles` option that can be set to TRUE if wanting to remove these files after install.

**Comment by zoidby** [comment]
I set `<SymLinkFilesFromCache>TRUE</SymLinkFilesFromCache>` and used `make-download-cache` for all installed tests.

But after that, the phoronix-test-suite uses even more space!

(And yes, i re-installed all tests for that.)

I can’t even install all the tests i had without the linking from cache. Even using hardlinks in addition is still bigger.

The only way to install all the tests i want is to not use the cache and hardlink bigger files by hand.
