### ISSUE TITLE
FORCE_TIMES_TO_RUN can be ignored?

### ISSUE THREAD

**Issue by SeanHeelan** [phoronix-test-suite/phoronix-test-suite#481]
Hey, 

I'm using Phoronix Test Suite v9.8.0 (Nesodden) and I've noticed that when running the `pts/renaissance` benchmark (UPDATE: I have since also seen this happen with the pts/apache benchmark, so it seems this isn't specific to pts/renaissance) sometimes I get far more benchmark executions than requested via the FORCE_TIMES_TO_RUN environment variable. 

I am executing the benchmark as follows (the `echo` being used to select a particular test):

```
echo "6" | PTS_SILENT_MODE=1 FORCE_TIMES_TO_RUN=3 ./phoronix-test-suite batch-run pts/renaissance
```

But for this run the output was 
```
Renaissance 0.10.0:
    pts/renaissance-1.1.1 [Test: Apache Spark PageRank]
    Test 1 of 1
    Estimated Trial Run Count:    3                      
    Estimated Time To Completion: 32 Minutes [22:38 UTC] 
        Started Run 1 @ 22:07:29
        Started Run 2 @ 22:10:43
        Started Run 3 @ 22:14:09
        Started Run 4 @ 22:17:38 *
        Started Run 5 @ 22:20:50 *
        Started Run 6 @ 22:24:12 *
        Started Run 7 @ 22:27:26 *
        Started Run 8 @ 22:31:00 *
        Started Run 9 @ 22:34:08 *
        Started Run 10 @ 22:37:17 *
        Started Run 11 @ 22:40:24 *
        Started Run 12 @ 22:43:21 *

    Test: Apache Spark PageRank:
        7346.11
        8461.291
        8113.001
        7052.162
        6947.874
        7476.31
        7600.812
        7598.36
        6726.271
        7334.1
        6127.321
        7962.692

    Average: 7395.525 ms
    Deviation: 8.59%
    Samples: 12
```

I've used the FORCE_TIMES_TO_RUN environment variable with quite a few other benchmarks and it always seems to work, so I am unsure if it is something to do with `pts/renaissance` or the fact that I'm using `echo` to select the test to run, or something else. 

I should probably note that _sometimes_ it will work, and I will get just the requested number of runs, but at least half the time I get more. The extra runs are always marked with an asterisk, as in the above output (I'm unsure what this indicates). 

Any idea what's going on?

Cheers,
Sean

**Comment by michaellarabel** [comment]
Hmmm, I am not aware of any issues around the FORCE_TIMES_TO_RUN handling nor have seen any similar reports of problems. There isn't any test-specific code that would affect just say Renaissance, but I added an extra safeguard now.

https://github.com/phoronix-test-suite/phoronix-test-suite/commit/48d74e52ce7a4249fb4d8f15c838767a59888a14 is a simple patch if wanting to apply on your own otherwise the PTS 10.2 release will have this additional layer of protection. That should fix the behavior you seem to be observing. This will basically ensure the dynamic run count handling is unconditionally disabled when FORCE_TIMES_TO_RUN is set.

**Comment by SeanHeelan** [comment]
Thanks!
