### ISSUE TITLE
install-debian-packages.sh should prefer sudo to su on crostini (Chrome OS)

### ISSUE THREAD

**Issue by hickford** [phoronix-test-suite/phoronix-test-suite#494]
https://github.com/phoronix-test-suite/phoronix-test-suite/blob/master/pts-core/external-test-dependencies/scripts/install-debian-packages.sh#L7 defaults to su rather than sudo ,  however this doesn't work on Chrome OS's default Debian installation (crostini) https://chromeos.dev/en/linux/setup#installing-linux-apps-and-packages

**Comment by michaellarabel** [comment]
Can you post the output of /phoronix-test-suite  diagnostics | grep OPERATING_SYSTEM  ??? Basically would need a way to reliably detect Crostini and with not using it myself not sure of the best means to do so off the top of my head. So ideally OPERATING_SYSTEM will be reported as Crostini or so rather than Debian.

**Comment by hickford** [comment]
$ phoronix-test-suite diagnostics | grep OPERATING_SYSTEM
    OPERATING_SYSTEM = Debian GNU/Linux 10
    OPERATING_SYSTEM = debian

One way is to check the existence of file /dev/.cros_milestone

**Comment by michaellarabel** [comment]
I see your commit, yeah something like that would work good enough if wanting to submit it as a pull request.
