### ISSUE TITLE
Failed PDF Export 10.2.0

### ISSUE THREAD

**Issue by calebcscott** [phoronix-test-suite/phoronix-test-suite#497]
I am receiving a php fatal error when attempting to use the sub-command `result-file-to-pdf`, the command `result-file-to-csv` worked without issues.

pts version: `Phoronix Test Suite v10.2.0 (Harstad)`

php version: `PHP 7.2.24-0ubuntu0.18.04.7 `

Error from pdf export:
```
PHP Fatal error:  Uncaught Error: Call to a member function get_max_value() on null in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php:360
Stack trace:
#0 /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_output.php(742): pts_result_file_analyzer::generate_executive_summary(Object(pts_result_file), NULL)
#1 /usr/share/phoronix-test-suite/pts-core/commands/result_file_to_pdf.php(49): pts_result_file_output::result_file_to_pdf(Object(pts_result_file), '/root/server-me...', 'F')
#2 /usr/share/phoronix-test-suite/pts-core/objects/client/pts_client.php(1524): result_file_to_pdf::run(Array)
#3 /usr/share/phoronix-test-suite/pts-core/phoronix-test-suite.php(152): pts_client::execute_command('result_file_to_...', Array)
#4 {main}
  thrown in /usr/share/phoronix-test-suite/pts-core/objects/pts_result_file_analyzer.php on line 360

    [NOTICE] Trying to get property 'test_result_buffer' of non-object in pts_result_file_analyzer:360

```

**Comment by michaellarabel** [comment]
Thanks for the report, from that output was able to figure out how depending upon the result file you were  trying to export could yield that error.

That error is now fixed in PTS Git if you are able to try that. Otherwise the PTS 10.2.1 release will be out in 1~2 weeks.

Or if you try with a larger result file with multiple runs, etc, that error should go away.

Thanks,
