### ISSUE TITLE
Understanding test profile options (multi-dimentional test results)

### ISSUE THREAD

**Issue by chfast** [phoronix-test-suite/phoronix-test-suite#517]
Hi there.

I'm working on an Interpreter project and there are also "competing" implementations of the same spec. I'd like to use PTS to:
- compare performance of the competing implementations,
- compare performance of my implementation versions,
- compare performance depending on compiler version and/or flags used.

I've found one example [system/selenium](https://github.com/phoronix-test-suite/test-profiles/blob/master/system/selenium-1.0.21/test-definition.xml) which is base around a benchmark suite but allows comparing different version of Firefox and Chrome.

I cannot run this test in the moment because I don't have a display. Are there other similar examples?

How this test profile knows how to run Firefox/Chrome and which version?

**Comment by michaellarabel** [comment]
"How this test profile knows how to run Firefox/Chrome and which version?"

That's all an implementation detail of the test. Selenium happens to look for whatever firefox or google-chrome is in PATH.

There are hundreds of other tests out there that expose multiple options at run-time like pyperformance or parboil or npb (among many other head-less tests for your case) and others but hard to provide any recommendation based on the limited description.

**Comment by chfast** [comment]
I will try to play with these and try to create my own benchmark suite for my software.

In case of `pyperformance` it also depends on `python` being available in PATH. Is there a way to test different `python` version with it?

Are there examples of test profiles which download both the benchmark suite (like pyperformence) but also can download the software being benchmarks (like python in this case)?

**Comment by michaellarabel** [comment]
"In case of pyperformance it also depends on python being available in PATH. Is there a way to test different python version with it?"

Yes, you just change your PATH environment variable being passed to the Phoronix Test Suite to instead have whatever preferred installed Python be first (or a symlink to a different one). Since PTS is used for a wide range of benchmarking and of different subsystems, etc for things such as that it will leave it up to what is used by the system and not enforcing/overriding any of its own policies.

In your case you could have it download an alternative binary for Python or whatever you want your test to do and then just handle it as a test option whether to say rely upon the system binary or use XYZ binary downloaded as part of the test profile. Should just be a simple bash script conditional statement. Once you get working on a test profile and run into any issues, posting it would likely be the easiest way for any feedback/guidance. Ultimately it should be very easy to test it as desired.
