### ISSUE TITLE
check for  "~/.phoronix-test-suite/skip-test " not only between test runs and/or resume test functionality 

### ISSUE THREAD

**Issue by FCLC** [phoronix-test-suite/phoronix-test-suite#575]
For certain test such as linpack amongst others, the time of each test run can run up to or exceed 1h of time. 

However PTS only checks for  ```~/.phoronix-test-suite/skip-test``` between test runs. 

This would mean that users would be tempted to either 

A: halt the benchmark overall, flag the test and start from scratch.
B: wait out the test and hope no other tests have been forgotten. 

Unfortunately the above options happen at every long test that users accidentally don't catch in time. 

the issue with this especially comes about when needing to test new systems/architectures where system memory, graphics cards, CPU's etc. need to be controlled and be identical for specific performance profiling in controlled environments. 

I'd like to propose the following solutions/request the following functionality:

1. A method to resume a manually halted test

 -  if a test is stopped at the terminal by a user via ^C, provide  a command of the style ```phoronix-test-suite resume-test [test identifier] ``` that would resume at last known good result -1. The user could then run ```~/.phoronix-test-suite/skip-test``` or ```~/.phoronix-test-suite/skip-next-test ``` to achieve the desired functionality 
 - - additional flag could be available to resume at a specific point to avoid having to use the skip test flag above. Something of the style ```phoronix-test-suite resume-test [test identifier] [test number at which to resume]```. For example if the problematic test was number 261/350, a user would be able to halt at 261, then resume at ```phoronix-test-suite resume-test [test identifier] [262]``

2. A watcher thread for ```~/.phoronix-test-suite/skip-test``` 
 - For any test where the estimated run time exceeds [time] add a watcher thread that checks for ```~/.phoronix-test-suite/skip-test``` every [time]/20

**Comment by michaellarabel** [comment]
The intended workflow would be (1) for manually halting the tests and then using the `finish-run` command, since chances are the user may be wanting to then skip multiple tests and/or make other test run option configuration changes, etc, if tests are taking too long to complete. There are the SKIP_TESTS= and SKIP_TESTS_HAVING_ARGS= env vars for helping with that skipping when finishing the run.

skip-test isn't polled during the actual testing to avoid the extra overhead for a seldom used feature as well as Windows and some other platforms not having PCNTL fork functionality needed to allow for the concurrent monitoring.
