### ISSUE TITLE
CS2 replay file pts29.dem no longer works

### ISSUE THREAD

**Issue by chan-nich** [phoronix-test-suite/phoronix-test-suite#787]
Previously the pts29.dem file referenced [here](https://openbenchmarking.org/innhold/7ece75e76fc661a112427a33ddb9b482b7cc59d8) was able to replay just fine and output the FPS to Source2Bench.csv. However, as of the [May 23rd patch](https://steamcommunity.com/games/CSGO/announcements/detail/4177730135016140041?snr=2___) it appears the layout for the de_vertigo map has changed - as a result the dem file can no longer be replayed as it fails to load a variety of resources from maps/de_vertigo/entities.

[ MAPS ]

Vertigo:
Added catwalk by bombsite A, connecting to back of A
Removed connector between back of A and elevators
Opened up passage between elevators and scaffolding
Slightly tweaked size of bombsite A
Tweaked spawn timings slightly
Changed Wingman layout to feature bombsite A changes

**Comment by chan-nich** [comment]
![pts29-errors](https://github.com/phoronix-test-suite/phoronix-test-suite/assets/88103175/f87fd57e-c2d1-4266-8b47-82da60aa06a7)

**Comment by Eliot-Roxbergh** [comment]
The benchmark does work on my machine (Debian Testing). I'm not very familiar with this, but tell me if there's something I should check.
I do however have an issue that after the run, the test suite never finishes and keeps waiting for output. I guess that, it's because the results are saved to _Source2Bench**V2**.csv_ instead of _Source2Bench.csv_.

**Comment by Eliot-Roxbergh** [comment]
This test works for me. I fixed the issue I had above: https://github.com/phoronix-test-suite/test-profiles/pull/313
