### ISSUE TITLE
Unigine benchmarks fail to install on Windows

### ISSUE THREAD

**Issue by rkingsbury** [phoronix-test-suite/phoronix-test-suite#82]
The various unigine benchmarks appear supported on windows (i.e. they appear when executing the list-tests command), but when I try to install them, PTS somehow skips the download. PTS acts as if the test had installed and gives normal output, but nothing is downloaded and running the test does not return any results. I tried unigine-heaven and unigine-valley. 

This occurs on 6.0 Milestone 1, downloaded from the website, on Windows 7. Other benchmarks (xonotic) download and install normally.

**Comment by michaellarabel** [comment]
For the larger Unigine Windows tests, you need to manually download the files and toss them in your user directory phoronix-test-suite/download-cache/ and then run the command again. Unfortunately for those Unigine Windows tests, there are no direct HTTP/FTP mirrors available but if you Google them you can find multiple download sources where you're able to manually get the files (geeks3d, techpowerup, etc). On Linux there isn't this issue as I mirror them directly since that support is more important.

**Comment by rkingsbury** [comment]
Thanks, Michael. That worked, but in addition to copying the downloaded file I had to manually install it onto the system before the test would run.

I understand Windows support is a 2nd priority, but I'd be happy to write some documentation about how to get these tests working. Where is the best place to do that? Should I submit a PR here, post something on the forums, etc?

**Comment by michaellarabel** [comment]
If it got confused on Windows afterwards, did you try: phoronix-test-suite force-install unigine-valley? The force-install would have forced it to be re-installed had  it gotten confused or if you had to first adjust the Windows priority levels.

Any documentation improvements would certainly be welcome. Either here via GitHub or in the forums. You can Take a look at the basic HTML markup supported via phoronix-test-suite/documentation/stubs (from there afterwards when running phoronix-test-suite dump-documentation it generates the PDF/MAN/HTML pages).

**Comment by rkingsbury** [comment]
Yes, I did try force-install. It copied the installer file from the download-cache/ directory into the actual test directory, but did not actually install anything. The terminal output indicated the test was installed, but it wouldn't run. 

Peeking at the .xml file associated with the test showed that it was pointing at the system directory C:\Program Files (x86)\Unigine ... etc. rather than the test directory inside .phoronix-test-suite. Is that normal? I was thinking most tests were run from inside .phoronix-test-suite directories.

**Comment by michaellarabel** [comment]
In order to run the Unigine MSI installer automatically, it uses the default installation patch, which puts it over in Program Files, etc. I'm not aware of any arguments for being able to alter the default install path while still being automated. It's just another issue with the Windows support being secondary / best effort in free time available, etc.

**Comment by rkingsbury** [comment]
Makes sense. I wonder if that was the problem - the download I found was an .exe installer. It sounds like PTS expects an MSI...
